name: 'PNPM install'
description: 'Run pnpm install with node_modules and cache enabled'

runs:
  using: 'composite'
  steps:
    - name: Set up pnpm
      uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
    - name: Set up Node.js
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version: lts/*
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm' # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies
    - name: Install dependencies
      env:
        HUSKY: '0' # By default do not run HUSKY install
      shell: bash
      run: pnpm install --frozen-lockfile
