packages:
  - packages/*
allowBuilds:
  msw: true
  nx: true
minimumReleaseAgeExclude:
  - '@bigmi/*'
  - '@lifi/*'
  - '@yuku-codegen/binding-darwin-arm64@0.6.1'
  - '@yuku-codegen/binding-darwin-x64@0.6.1'
  - '@yuku-codegen/binding-freebsd-x64@0.6.1'
  - '@yuku-codegen/binding-linux-arm-gnu@0.6.1'
  - '@yuku-codegen/binding-linux-arm-musl@0.6.1'
  - '@yuku-codegen/binding-linux-arm64-gnu@0.6.1'
  - '@yuku-codegen/binding-linux-arm64-musl@0.6.1'
  - '@yuku-codegen/binding-linux-x64-gnu@0.6.1'
  - '@yuku-codegen/binding-linux-x64-musl@0.6.1'
  - '@yuku-codegen/binding-win32-arm64@0.6.1'
  - '@yuku-codegen/binding-win32-x64@0.6.1'
  - '@yuku-parser/binding-darwin-arm64@0.6.1'
  - '@yuku-parser/binding-darwin-x64@0.6.1'
  - '@yuku-parser/binding-freebsd-x64@0.6.1'
  - '@yuku-parser/binding-linux-arm-gnu@0.6.1'
  - '@yuku-parser/binding-linux-arm-musl@0.6.1'
  - '@yuku-parser/binding-linux-arm64-gnu@0.6.1'
  - '@yuku-parser/binding-linux-arm64-musl@0.6.1'
  - '@yuku-parser/binding-linux-x64-gnu@0.6.1'
  - '@yuku-parser/binding-linux-x64-musl@0.6.1'
  - '@yuku-parser/binding-win32-arm64@0.6.1'
  - '@yuku-parser/binding-win32-x64@0.6.1'
  - rolldown-plugin-dts@0.27.8
  - tsdown@0.22.7
  - yuku-codegen@0.6.1
  - yuku-parser@0.6.1
overrides:
  axios: ^1.16.0
