packages:
  - packages/*
allowBuilds:
  msw: true
  nx: true
minimumReleaseAgeExclude:
  - '@bigmi/*'
  - '@lifi/*'
  - '@stellar/stellar-sdk@17.2.0'
  - '@types/ws@8.18.2'
  - msw@3.0.0
  - viem@2.57.0
overrides:
  axios: ^1.20.0
  ws@<=8.22.0: 8.22.0
